version: '3.1'
services:
  fakesmtp:
    image: munkyboy/fakesmtp
    ports:
      - "2525:25"
    volumes:
      - $HOME/.docker-stuff/fakesmtp:/var/mail
    networks:
      - ducode_default

networks:
  ducode_default:
    external: true