version: '3.1'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password123!
      MSSQL_PID: Developer
    ports:
      - 1433:1433
    volumes:
      - $HOME/.docker-stuff/mssql:/var/opt/mssql