version: '3.1'
services:
  mysql:
    image: mysql:5.7.28
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - $HOME/.docker-stuff/mysql:/var/lib/mysql
    networks:
      - ducode_default

networks:
  ducode_default:
    external: true