version: '3.1'
services:
  mysql:
    image: mysql:5.7.28
    command: --default-authentication-plugin=mysql_native_password --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - $HOME/.docker-stuff/mysql:/var/lib/mysql
    networks:
      - ducode_default

networks:
  ducode_default:
    external: true